{
  products(
    filter: {
      sku: { in: ["24-WG01", "24-WG02", "WJ02", "24-WG080", "GC-BUNDLE-FIXED", "24-WG085_Group", "240-LV04", "MH01"] }
    }
    pageSize: 20
  ) {
    items {
      activity
      attribute_set_id
      canonical_url
      categories {
        available_sort_by
        canonical_url
        children_count
        cms_block {
          content
          identifier
          title
        }
        created_at
        custom_layout_update_file
        description
        display_mode
        filter_price_range
        id
        image
        include_in_menu
        is_anchor
        landing_page
        level
        meta_description
        meta_keywords
        meta_title
        name
        path
        path_in_store
        position
        product_count
        uid
        updated_at
        url_key
        url_path
        url_suffix
      }
      category_gear
      climate
      collar
      color
      country_of_manufacture
      created_at
      crosssell_products {
        sku
      }
      custom_attributesV2 {
        errors {
          message
        }
        items {
          code
          ... on AttributeValue {
            attributevalue_value: value
          }
          ... on AttributeSelectedOptions {
            attributeselectedoptions_selected_options: selected_options {
              label
              value
            }
          }
        }
      }
      description {
        html
      }
      eco_collection
      erin_recommends
      features_bags
      format
      gender
      gift_message_available
      id
      image {
        disabled
        label
        position
        types
        url
      }
      manufacturer
      material
      max_sale_qty
      media_gallery {
        disabled
        label
        position
        types
        url
        ... on ProductVideo {
          productvideo_video_content: video_content {
            media_type
            video_description
            video_metadata
            video_provider
            video_title
            video_url
          }
        }
      }
      media_gallery_entries {
        content {
          base64_encoded_data
          name
        }
        disabled
        file
        label
        media_type
        position
        types
        video_content {
          media_type
          video_description
          video_metadata
          video_provider
          video_title
          video_url
        }
      }
      meta_description
      meta_keyword
      meta_title
      min_sale_qty
      name
      new
      new_from_date
      new_to_date
      only_x_left_in_stock
      options_container
      pattern
      performance_fabric
      price {
        maximalPrice {
          adjustments {
            amount {
              currency
              value
            }
            code
            description
          }
          amount {
            currency
            value
          }
        }
        minimalPrice {
          adjustments {
            amount {
              currency
              value
            }
            code
            description
          }
          amount {
            currency
            value
          }
        }
        regularPrice {
          adjustments {
            amount {
              currency
              value
            }
            code
            description
          }
          amount {
            currency
            value
          }
        }
      }
      price_range {
        maximum_price {
          discount {
            amount_off
            percent_off
          }
          final_price {
            currency
            value
          }
          fixed_product_taxes {
            amount {
              currency
              value
            }
            label
          }
          regular_price {
            currency
            value
          }
        }
        minimum_price {
          discount {
            amount_off
            percent_off
          }
          final_price {
            currency
            value
          }
          fixed_product_taxes {
            amount {
              currency
              value
            }
            label
          }
          regular_price {
            currency
            value
          }
        }
      }
      price_tiers {
        discount {
          amount_off
          percent_off
        }
        final_price {
          currency
          value
        }
        quantity
      }
      quantity
      rating_summary
      related_products {
        sku
      }
      review_count
      reviews {
        items {
          average_rating
          created_at
          nickname
          product {
            sku
          }
          ratings_breakdown {
            name
            value
          }
          summary
          text
        }
        page_info {
          current_page
          page_size
          total_pages
        }
      }
      sale
      short_description {
        html
      }
      size
      sku
      sleeve
      small_image {
        disabled
        label
        position
        types
        url
      }
      special_from_date
      special_price
      special_to_date
      stock_status
      strap_bags
      style_bags
      style_bottom
      style_general
      swatch_image
      thumbnail {
        disabled
        label
        position
        types
        url
      }
      tier_price
      tier_prices {
        customer_group_id
        percentage_value
        qty
        value
        website_id
      }
      type_id
      uid
      updated_at
      upsell_products {
        sku
      }
      url_key
      url_path
      url_rewrites {
        parameters {
          name
          value
        }
        url
      }
      url_suffix
      websites {
        code
        default_group_id
        id
        is_default
        name
        sort_order
      }
      ... on VirtualProduct {
        virtualproduct_options: options {
          option_id
          required
          sort_order
          title
          uid
          ... on CustomizableAreaOption {
            customizableareaoption_product_sku: product_sku
            customizableareaoption_value: value {
              max_characters
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableDateOption {
            customizabledateoption_product_sku: product_sku
            customizabledateoption_value: value {
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableDropDownOption {
            customizabledropdownoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableMultipleOption {
            customizablemultipleoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableFieldOption {
            customizablefieldoption_product_sku: product_sku
            customizablefieldoption_value: value {
              max_characters
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableFileOption {
            customizablefileoption_product_sku: product_sku
            customizablefileoption_value: value {
              file_extension
              image_size_x
              image_size_y
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableRadioOption {
            customizableradiooption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableCheckboxOption {
            customizablecheckboxoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
        }
      }
      ... on SimpleProduct {
        simpleproduct_options: options {
          option_id
          required
          sort_order
          title
          uid
          ... on CustomizableAreaOption {
            customizableareaoption_product_sku: product_sku
            customizableareaoption_value: value {
              max_characters
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableDateOption {
            customizabledateoption_product_sku: product_sku
            customizabledateoption_value: value {
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableDropDownOption {
            customizabledropdownoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableMultipleOption {
            customizablemultipleoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableFieldOption {
            customizablefieldoption_product_sku: product_sku
            customizablefieldoption_value: value {
              max_characters
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableFileOption {
            customizablefileoption_product_sku: product_sku
            customizablefileoption_value: value {
              file_extension
              image_size_x
              image_size_y
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableRadioOption {
            customizableradiooption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableCheckboxOption {
            customizablecheckboxoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
        }
        simpleproduct_weight: weight
      }
      ... on DownloadableProduct {
        downloadableproduct_downloadable_product_links: downloadable_product_links {
          id
          is_shareable
          link_type
          number_of_downloads
          price
          sample_file
          sample_type
          sample_url
          sort_order
          title
          uid
        }
        downloadableproduct_downloadable_product_samples: downloadable_product_samples {
          id
          sample_file
          sample_type
          sample_url
          sort_order
          title
        }
        downloadableproduct_links_purchased_separately: links_purchased_separately
        downloadableproduct_links_title: links_title
        downloadableproduct_options: options {
          option_id
          required
          sort_order
          title
          uid
          ... on CustomizableAreaOption {
            customizableareaoption_product_sku: product_sku
            customizableareaoption_value: value {
              max_characters
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableDateOption {
            customizabledateoption_product_sku: product_sku
            customizabledateoption_value: value {
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableDropDownOption {
            customizabledropdownoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableMultipleOption {
            customizablemultipleoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableFieldOption {
            customizablefieldoption_product_sku: product_sku
            customizablefieldoption_value: value {
              max_characters
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableFileOption {
            customizablefileoption_product_sku: product_sku
            customizablefileoption_value: value {
              file_extension
              image_size_x
              image_size_y
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableRadioOption {
            customizableradiooption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableCheckboxOption {
            customizablecheckboxoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
        }
      }
      ... on BundleProduct {
        bundleproduct_dynamic_price: dynamic_price
        bundleproduct_dynamic_sku: dynamic_sku
        bundleproduct_dynamic_weight: dynamic_weight
        bundleproduct_items: items {
          option_id
          options {
            can_change_quantity
            id
            is_default
            label
            position
            price
            price_type
            product {
              sku
            }
            qty
            quantity
            uid
          }
          position
          required
          sku
          title
          uid
        }
        bundleproduct_options: options {
          option_id
          required
          sort_order
          title
          uid
          ... on CustomizableAreaOption {
            customizableareaoption_product_sku: product_sku
            customizableareaoption_value: value {
              max_characters
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableDateOption {
            customizabledateoption_product_sku: product_sku
            customizabledateoption_value: value {
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableDropDownOption {
            customizabledropdownoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableMultipleOption {
            customizablemultipleoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableFieldOption {
            customizablefieldoption_product_sku: product_sku
            customizablefieldoption_value: value {
              max_characters
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableFileOption {
            customizablefileoption_product_sku: product_sku
            customizablefileoption_value: value {
              file_extension
              image_size_x
              image_size_y
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableRadioOption {
            customizableradiooption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableCheckboxOption {
            customizablecheckboxoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
        }
        bundleproduct_price_details: price_details {
          discount_percentage
          main_final_price
          main_price
        }
        bundleproduct_price_view: price_view
        bundleproduct_ship_bundle_items: ship_bundle_items
        bundleproduct_weight: weight
      }
      ... on GroupedProduct {
        groupedproduct_items: items {
          position
          product {
            sku
          }
        }
        groupedproduct_weight: weight
      }
      ... on ConfigurableProduct {
        configurableproduct_configurable_options: configurable_options {
          attribute_code
          attribute_id
          attribute_id_v2
          attribute_uid
          id
          label
          position
          product_id
          uid
          use_default
          values {
            default_label
            label
            store_label
            swatch_data {
              value
              ... on ImageSwatchData {
                imageswatchdata_thumbnail: thumbnail
              }
            }
            uid
            use_default_value
            value_index
          }
        }
        configurableproduct_configurable_product_options_selection: configurable_product_options_selection {
          configurable_options {
            attribute_code
            label
            uid
            values {
              is_available
              is_use_default
              label
              swatch {
                value
                ... on ImageSwatchData {
                  imageswatchdata_thumbnail: thumbnail
                }
              }
              uid
            }
          }
          media_gallery {
            disabled
            label
            position
            types
            url
            ... on ProductVideo {
              productvideo_video_content: video_content {
                media_type
                video_description
                video_metadata
                video_provider
                video_title
                video_url
              }
            }
          }
          options_available_for_selection {
            attribute_code
            option_value_uids
          }
          variant {
            activity
            attribute_set_id
            canonical_url
            categories {
              available_sort_by
              canonical_url
              children_count
              cms_block {
                content
                identifier
                title
              }
              created_at
              custom_layout_update_file
              description
              display_mode
              filter_price_range
              id
              image
              include_in_menu
              is_anchor
              landing_page
              level
              meta_description
              meta_keywords
              meta_title
              name
              path
              path_in_store
              position
              product_count
              uid
              updated_at
              url_key
              url_path
              url_suffix
            }
            category_gear
            climate
            collar
            color
            country_of_manufacture
            created_at
            crosssell_products {
              sku
            }
            custom_attributesV2 {
              errors {
                message
              }
              items {
                code
                ... on AttributeValue {
                  attributevalue_value: value
                }
              }
            }
            description {
              html
            }
            eco_collection
            erin_recommends
            features_bags
            format
            gender
            gift_message_available
            id
            image {
              disabled
              label
              position
              types
              url
            }
            manufacturer
            material
            max_sale_qty
            media_gallery {
              disabled
              label
              position
              types
              url
              ... on ProductVideo {
                productvideo_video_content: video_content {
                  media_type
                  video_description
                  video_metadata
                  video_provider
                  video_title
                  video_url
                }
              }
            }
            media_gallery_entries {
              content {
                base64_encoded_data
                name
              }
              disabled
              file
              label
              media_type
              position
              types
              video_content {
                media_type
                video_description
                video_metadata
                video_provider
                video_title
                video_url
              }
            }
            meta_description
            meta_keyword
            meta_title
            min_sale_qty
            name
            new
            new_from_date
            new_to_date
            only_x_left_in_stock
            options {
              option_id
              required
              sort_order
              title
              uid
              ... on CustomizableAreaOption {
                customizableareaoption_product_sku: product_sku
                customizableareaoption_value: value {
                  max_characters
                  price
                  price_type
                  sku
                  uid
                }
              }
              ... on CustomizableDateOption {
                customizabledateoption_product_sku: product_sku
                customizabledateoption_value: value {
                  price
                  price_type
                  sku
                  uid
                }
              }
              ... on CustomizableDropDownOption {
                customizabledropdownoption_value: value {
                  option_type_id
                  price
                  price_type
                  sku
                  sort_order
                  title
                  uid
                }
              }
              ... on CustomizableMultipleOption {
                customizablemultipleoption_value: value {
                  option_type_id
                  price
                  price_type
                  sku
                  sort_order
                  title
                  uid
                }
              }
              ... on CustomizableFieldOption {
                customizablefieldoption_product_sku: product_sku
                customizablefieldoption_value: value {
                  max_characters
                  price
                  price_type
                  sku
                  uid
                }
              }
              ... on CustomizableFileOption {
                customizablefileoption_product_sku: product_sku
                customizablefileoption_value: value {
                  file_extension
                  image_size_x
                  image_size_y
                  price
                  price_type
                  sku
                  uid
                }
              }
              ... on CustomizableRadioOption {
                customizableradiooption_value: value {
                  option_type_id
                  price
                  price_type
                  sku
                  sort_order
                  title
                  uid
                }
              }
              ... on CustomizableCheckboxOption {
                customizablecheckboxoption_value: value {
                  option_type_id
                  price
                  price_type
                  sku
                  sort_order
                  title
                  uid
                }
              }
            }
            options_container
            pattern
            performance_fabric
            price_tiers {
              discount {
                amount_off
                percent_off
              }
              final_price {
                currency
                value
              }
              quantity
            }
            quantity
            rating_summary
            related_products {
              sku
            }
            review_count
            reviews {
              items {
                average_rating
                created_at
                nickname
                product {
                  sku
                }
                summary
                text
              }
              page_info {
                current_page
                page_size
                total_pages
              }
            }
            sale
            short_description {
              html
            }
            size
            sku
            sleeve
            small_image {
              disabled
              label
              position
              types
              url
            }
            special_from_date
            special_price
            special_to_date
            stock_status
            strap_bags
            style_bags
            style_bottom
            style_general
            swatch_image
            thumbnail {
              disabled
              label
              position
              types
              url
            }
            tier_price
            tier_prices {
              customer_group_id
              percentage_value
              qty
              value
              website_id
            }
            type_id
            uid
            updated_at
            upsell_products {
              sku
            }
            url_key
            url_path
            url_rewrites {
              parameters {
                name
                value
              }
              url
            }
            url_suffix
            weight
          }
        }
        configurableproduct_options: options {
          option_id
          required
          sort_order
          title
          uid
          ... on CustomizableAreaOption {
            customizableareaoption_product_sku: product_sku
            customizableareaoption_value: value {
              max_characters
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableDateOption {
            customizabledateoption_product_sku: product_sku
            customizabledateoption_value: value {
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableDropDownOption {
            customizabledropdownoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableMultipleOption {
            customizablemultipleoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableFieldOption {
            customizablefieldoption_product_sku: product_sku
            customizablefieldoption_value: value {
              max_characters
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableFileOption {
            customizablefileoption_product_sku: product_sku
            customizablefileoption_value: value {
              file_extension
              image_size_x
              image_size_y
              price
              price_type
              sku
              uid
            }
          }
          ... on CustomizableRadioOption {
            customizableradiooption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
          ... on CustomizableCheckboxOption {
            customizablecheckboxoption_value: value {
              option_type_id
              price
              price_type
              sku
              sort_order
              title
              uid
            }
          }
        }
        configurableproduct_variants: variants {
          attributes {
            code
            label
            uid
            value_index
          }
          product {
            activity
            attribute_set_id
            canonical_url
            categories {
              available_sort_by
              canonical_url
              children_count
              cms_block {
                content
                identifier
                title
              }
              created_at
              custom_layout_update_file
              description
              display_mode
              filter_price_range
              id
              image
              include_in_menu
              is_anchor
              landing_page
              level
              meta_description
              meta_keywords
              meta_title
              name
              path
              path_in_store
              position
              product_count
              uid
              updated_at
              url_key
              url_path
              url_suffix
            }
            category_gear
            climate
            collar
            color
            country_of_manufacture
            created_at
            crosssell_products {
              sku
            }
            custom_attributesV2 {
              errors {
                message
              }
              items {
                code
                ... on AttributeValue {
                  attributevalue_value: value
                }
              }
            }
            description {
              html
            }
            eco_collection
            erin_recommends
            features_bags
            format
            gender
            gift_message_available
            id
            image {
              disabled
              label
              position
              types
              url
            }
            manufacturer
            material
            max_sale_qty
            media_gallery {
              disabled
              label
              position
              types
              url
              ... on ProductVideo {
                productvideo_video_content: video_content {
                  media_type
                  video_description
                  video_metadata
                  video_provider
                  video_title
                  video_url
                }
              }
            }
            media_gallery_entries {
              content {
                base64_encoded_data
                name
              }
              disabled
              file
              label
              media_type
              position
              types
              video_content {
                media_type
                video_description
                video_metadata
                video_provider
                video_title
                video_url
              }
            }
            meta_description
            meta_keyword
            meta_title
            min_sale_qty
            name
            new
            new_from_date
            new_to_date
            only_x_left_in_stock
            options {
              option_id
              required
              sort_order
              title
              uid
              ... on CustomizableAreaOption {
                customizableareaoption_product_sku: product_sku
                customizableareaoption_value: value {
                  max_characters
                  price
                  price_type
                  sku
                  uid
                }
              }
              ... on CustomizableDateOption {
                customizabledateoption_product_sku: product_sku
                customizabledateoption_value: value {
                  price
                  price_type
                  sku
                  uid
                }
              }
              ... on CustomizableDropDownOption {
                customizabledropdownoption_value: value {
                  option_type_id
                  price
                  price_type
                  sku
                  sort_order
                  title
                  uid
                }
              }
              ... on CustomizableMultipleOption {
                customizablemultipleoption_value: value {
                  option_type_id
                  price
                  price_type
                  sku
                  sort_order
                  title
                  uid
                }
              }
              ... on CustomizableFieldOption {
                customizablefieldoption_product_sku: product_sku
                customizablefieldoption_value: value {
                  max_characters
                  price
                  price_type
                  sku
                  uid
                }
              }
              ... on CustomizableFileOption {
                customizablefileoption_product_sku: product_sku
                customizablefileoption_value: value {
                  file_extension
                  image_size_x
                  image_size_y
                  price
                  price_type
                  sku
                  uid
                }
              }
              ... on CustomizableRadioOption {
                customizableradiooption_value: value {
                  option_type_id
                  price
                  price_type
                  sku
                  sort_order
                  title
                  uid
                }
              }
              ... on CustomizableCheckboxOption {
                customizablecheckboxoption_value: value {
                  option_type_id
                  price
                  price_type
                  sku
                  sort_order
                  title
                  uid
                }
              }
            }
            options_container
            pattern
            performance_fabric
            price_tiers {
              discount {
                amount_off
                percent_off
              }
              final_price {
                currency
                value
              }
              quantity
            }
            quantity
            rating_summary
            related_products {
              sku
            }
            review_count
            reviews {
              items {
                average_rating
                created_at
                nickname
                product {
                  sku
                }
                summary
                text
              }
              page_info {
                current_page
                page_size
                total_pages
              }
            }
            sale
            short_description {
              html
            }
            size
            sku
            sleeve
            small_image {
              disabled
              label
              position
              types
              url
            }
            special_from_date
            special_price
            special_to_date
            stock_status
            strap_bags
            style_bags
            style_bottom
            style_general
            swatch_image
            thumbnail {
              disabled
              label
              position
              types
              url
            }
            tier_price
            tier_prices {
              customer_group_id
              percentage_value
              qty
              value
              website_id
            }
            type_id
            uid
            updated_at
            upsell_products {
              sku
            }
            url_key
            url_path
            url_rewrites {
              parameters {
                name
                value
              }
              url
            }
            url_suffix
            weight
          }
        }
        configurableproduct_weight: weight
      }
    }
  }
}
