query {
  products(filter: { sku: { in: [{{skus:any:fpt:6}}] } }, pageSize: 20) {
    items {
      sku __typename
      price_range {
        minimum_price {
          regular_price { value currency } final_price { value currency } discount { amount_off percent_off }
          fixed_product_taxes { amount { value currency } label }
        }
        maximum_price {
          regular_price { value currency } final_price { value currency } discount { amount_off percent_off }
          fixed_product_taxes { amount { value currency } label }
        }
      }
      price { minimalPrice { amount { value currency } adjustments { code amount { value currency } description } } regularPrice { amount { value currency } adjustments { code amount { value currency } description } } maximalPrice { amount { value currency } adjustments { code amount { value currency } description } } }
      price_tiers { discount { amount_off percent_off } quantity final_price { value currency } }
    }
  }
}
