<?php
declare(strict_types=1);

namespace GraphCommerce\CatalogStorefrontProductFrontend\Test\Unit\Plugin\Listing;

use GraphCommerce\CatalogStorefrontProductFrontend\Model\Read\ListingDocuments;
use GraphCommerce\CatalogStorefrontProductFrontend\Plugin\Listing\UrlRewritesFromDocuments;
use Magento\Framework\Serialize\Serializer\Json;
use Magento\Store\Api\Data\StoreInterface;
use Magento\Store\Model\StoreManagerInterface;
use Magento\UrlRewrite\Model\UrlFinderInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;
use PHPUnit\Framework\TestCase;

class UrlRewritesFromDocumentsTest extends TestCase
{
    private ListingDocuments $listing;

    private bool $coreAsked = false;

    private function plugin(bool $documents = true): UrlRewritesFromDocuments
    {
        $this->listing = new ListingDocuments();
        $this->listing->add('default', [
            1 => ['urlRewrites' => [
                ['url' => 'https://shop.example/bag.html', 'parameters' => [['name' => 'id', 'value' => '1']]],
                ['url' => 'https://shop.example/gear/bag.html', 'parameters' => [['name' => 'id', 'value' => '1'], ['name' => 'category', 'value' => '5']]],
            ]],
            2 => ['urlRewrites' => []],
        ]);

        $store = $this->createMock(StoreInterface::class);
        $store->method('getCode')->willReturn('default');
        $storeManager = $this->createMock(StoreManagerInterface::class);
        $storeManager->method('getStore')->willReturn($store);

        $factory = $this->createMock(UrlRewriteFactory::class);
        $factory->method('create')->willReturnCallback(static fn () => new UrlRewrite([], new Json()));

        $mode = $this->createStub(\GraphCommerce\CatalogStorefrontProductFrontend\Model\Mode::class);
        $mode->method('listing')->willReturn($documents);
        return new UrlRewritesFromDocuments($this->listing, $storeManager, $factory, $mode);
    }

    /**
     * @return array<int, string> request path by product id
     */
    private function find(UrlRewritesFromDocuments $plugin, array $data): array
    {
        $rewrites = $plugin->aroundFindAllByData(
            $this->createMock(UrlFinderInterface::class),
            function () {
                $this->coreAsked = true;

                return [];
            },
            $data
        );
        $paths = [];
        foreach ($rewrites as $rewrite) {
            $paths[$rewrite->getEntityId()] = $rewrite->getRequestPath();
        }

        return $paths;
    }

    public function testTheRewriteWithoutACategoryAnswersAPlainProductUrl(): void
    {
        $paths = $this->find($this->plugin(), ['entity_type' => 'product', 'entity_id' => [1, 2], 'store_id' => 1, 'is_autogenerated' => 1]);

        $this->assertSame([1 => 'bag.html'], $paths);
        $this->assertFalse($this->coreAsked);
    }

    public function testTheRewriteOfTheCategoryAnswersACategoryPathUrl(): void
    {
        $paths = $this->find($this->plugin(), ['entity_type' => 'product', 'entity_id' => [1], 'store_id' => 1, 'is_autogenerated' => 1, 'metadata' => ['category_id' => 5]]);

        $this->assertSame([1 => 'gear/bag.html'], $paths);
    }

    public function testAMissingProductDocumentFails(): void
    {
        $this->expectException(\GraphCommerce\CatalogStorefront\Model\DocumentReadException::class);
        try {
            $this->find($this->plugin(), ['entity_type' => 'product', 'entity_id' => [1, 9], 'store_id' => 1]);
        } finally {
            self::assertFalse($this->coreAsked);
        }
    }

    public function testCoreModeUsesCore(): void
    {
        $this->find($this->plugin(false), ['entity_type' => 'product', 'entity_id' => [1, 9], 'store_id' => 1]);
        self::assertTrue($this->coreAsked);
    }

    public function testARequestWithoutADocumentListingUsesCore(): void
    {
        $plugin = $this->plugin();
        $this->listing->_resetState();
        $this->find($plugin, ['entity_type' => 'product', 'entity_id' => [1], 'store_id' => 1]);
        self::assertTrue($this->coreAsked);
    }

    public function testACategoryLookupIsUntouched(): void
    {
        $this->find($this->plugin(), ['entity_type' => 'category', 'entity_id' => [1], 'store_id' => 1]);

        $this->assertTrue($this->coreAsked);
    }
}
